title: Yueran PAN
description: |
  PhD student in Computer Science, jointly trained by DKU&WHU/
  RA at DKU/ 
  MSc Data Science at LSE/ 
  BSc Statistics at WHU/ 
  Project under Microsoft Research/ 
  Data Analysis Intern at Tencent

theme: jekyll-theme-minimal
logo: pyr_wanlin.jpg

