title: Yueran PAN
description: CS PhD student at WHU/ RA at DKU/ MSc Data Science at LSE/ BSc Statistics at WHU/ Project under Microsoft Research/ Data Analysis Intern at Tencent

theme: jekyll-theme-minimal
logo: pyr_wanlin.jpg

