title: Yueran PAN
description: |
  AI Product Manager for Yuanbao at Tencent
  AI Researcher in Evaluation & Test Engineering at Midea
  Research Assistant in Computer Science at Duke Kunshan University & Wuhan University
  MSc in Data Science, London School of Economics and Political Science
  BSc in Statistics, Wuhan University
  Research Project with Microsoft Research Cambridge, UK
  Data Analysis Intern at Tencent

theme: jekyll-theme-minimal
logo: pyr_wanlin.jpg

